## SVM for regression

In [17]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [18]:
df = pd.read_csv("Movie_regression.csv", header = 0)

In [19]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  
0          223.840  Thriller              23            494       48000  
1          243.456     Drama              42            462       43200  
2         2022.400    Comedy              38            458       69400  
3          225.344     Drama              45            472       66800  
4          225.792     Drama              55            395       72400

In [20]:
df.describe()

Marketing expense  Production expense  Multiplex coverage  \
count         506.000000          506.000000          506.000000   
mean           92.270471           77.273557            0.445305   
std           172.030902           13.720706            0.115878   
min            20.126400           55.920000            0.129000   
25%            21.640900           65.380000            0.376000   
50%            25.130200           74.380000            0.462000   
75%            93.541650           91.200000            0.551000   
max          1799.524000          110.480000            0.615000   

             Budget  Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  \
count    506.000000    506.000000          506.000000           506.000000   
mean   34911.144022    142.074901            8.014002             8.185613   
std     3903.038232     28.148861            1.054266             1.054290   
min    19781.355000     76.400000            3.840000             4.035000   
25%    32693.952500    118.525000            7.316250             7.503750   
50%    34488.217500    151.000000            8.307500             8.495000   
75%    36793.542500    167.575000            8.865000             9.030000   
max    48772.900000    173.500000            9.435000             9.540000   

       Director_rating  Producer_rating  Critic_rating  Trailer_views  \
count       506.000000       506.000000     506.000000     506.000000   
mean          8.019664         8.190514       7.810870  449860.715415   
std           1.059899         1.049601       0.659699   68917.763145   
min           3.840000         4.030000       6.600000  212912.000000   
25%           7.296250         7.507500       7.200000  409128.000000   
50%           8.312500         8.465000       7.960000  462460.000000   
75%           8.883750         9.030000       8.260000  500247.500000   
max           9.425000         9.635000       9.400000  567784.000000   

       Time_taken  Twitter_hastags  Avg_age_actors  Num_multiplex  \
count  494.000000       506.000000      506.000000     506.000000   
mean   157.391498       260.832095       39.181818     545.043478   
std     31.295161       104.779133       12.513697     106.332889   
min      0.000000       201.152000        3.000000     333.000000   
25%    132.300000       223.796000       28.000000     465.000000   
50%    160.000000       254.400000       39.000000     535.500000   
75%    181.890000       283.416000       50.000000     614.750000   
max    217.520000      2022.400000       60.000000     868.000000   

          Collection  
count     506.000000  
mean    45057.707510  
std     18364.351764  
min     10000.000000  
25%     34050.000000  
50%     42400.000000  
75%     50000.000000  
max    100000.000000

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

In [22]:
#filling na
df["Time_taken"] = df.Time_taken.fillna(np.mean(df.Time_taken))

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           506 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

In [24]:
# creating dummy variables
df = pd.get_dummies(df, columns = ["3D_available", "Genre"], drop_first=True)

In [25]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views  Time_taken  Twitter_hastags  \
0            7.995           7.94         527367      109.60          223.840   
1            7.470           7.44         494055      146.64          243.456   
2            7.515           7.44         547051      147.88         2022.400   
3            7.020           8.26         516279      185.36          225.344   
4            7.070           8.26         531448      176.48          225.792   

   Avg_age_actors  Num_multiplex  Collection  3D_available_YES  Genre_Comedy  \
0              23            494       48000                 1             0   
1              42            462       43200                 0             0   
2              38            458       69400                 0             1   
3              45            472       66800                 1             0   
4              55            395       72400                 0             0   

   Genre_Drama  Genre_Thriller  
0            0               1  
1            1               0  
2            0               0  
3            1               0  
4            1               0

In [26]:
#X-y split
X = df.loc[:, df.columns!="Collection"]
y = df["Collection"]

In [27]:
X.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views  Time_taken  Twitter_hastags  \
0            7.995           7.94         527367      109.60          223.840   
1            7.470           7.44         494055      146.64          243.456   
2            7.515           7.44         547051      147.88         2022.400   
3            7.020           8.26         516279      185.36          225.344   
4            7.070           8.26         531448      176.48          225.792   

   Avg_age_actors  Num_multiplex  3D_available_YES  Genre_Comedy  Genre_Drama  \
0              23            494                 1             0            0   
1              42            462                 0             0            1   
2              38            458                 0             1            0   
3              45            472                 1             0            1   
4              55            395                 0             0            1   

   Genre_Thriller  
0               1  
1               0  
2               0  
3               0  
4               0

In [28]:
y

0      48000
1      43200
2      69400
3      66800
4      72400
       ...  
501    44800
502    41200
503    47800
504    44000
505    38000
Name: Collection, Length: 506, dtype: int64

In [29]:
#Train-test split
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [33]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(404, 19) (102, 19) (404,) (102,)


### Standardize the data

Standardize the data because SVM will only give correct results when we standardize the data, since we will calculate distances
from the margin, and distance is dependent on each variable scale. If you do not standardize the data, the variable with higher scale will have much more impact than the one with lower scale 

Standardization of the data means to make mean equals 0 and STD equals 1

In [34]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler().fit(X_train)

In [35]:
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [36]:
X_train_std

array([[-0.37257438, -0.70492455,  0.42487874, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39709866, -0.04487755,  1.24185891, ..., -0.66547513,
        -0.48525664, -0.75225758],
       [-0.402693  , -0.88675963,  1.11148974, ...,  1.50268577,
        -0.48525664, -0.75225758],
       ...,
       [-0.39805586, -0.15941933,  0.0772276 , ..., -0.66547513,
        -0.48525664, -0.75225758],
       [-0.38842357, -0.60326872,  0.93766417, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39951258, -1.01275558,  0.3988049 , ..., -0.66547513,
        -0.48525664,  1.3293319 ]])

In [37]:
X_test_std

array([[-0.40835869, -1.12872913,  0.83336883, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [ 0.71925111,  0.9988844 , -0.65283979, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40257488,  0.39610829,  0.05115377, ...,  1.50268577,
        -0.48525664, -0.75225758],
       ...,
       [-0.3982601 , -0.85812418,  0.89420778, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39934279, -0.07637654,  0.58132175, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40088071, -0.36702631,  0.31189212, ..., -0.66547513,
        -0.48525664, -0.75225758]])

### Training the model

In [38]:
#import support vector function for regression
from sklearn.svm import SVR

In [40]:
svr = SVR(kernel = "linear", C = 1000) #create an object classifier with hyperparameters kernel linear and Cost = 1000

In [41]:
svr.fit(X_train_std, y_train)

SVR(C=1000, kernel='linear')

In [47]:
#predict values
y_pred = svr.predict(X_test_std)

In [43]:
#evaluate model performance
from sklearn.metrics import r2_score, mean_squared_error

In [48]:
r2_score(y_test, y_pred)

0.5025135728682528

In [49]:
mean_squared_error(y_test, y_pred) #mse are compared between models and not with any other metrics because it is an absolute value

160153135.39405018

## SVM for classification

In [51]:
df = pd.read_csv("Movie_classification.csv", header = 0)

In [53]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840  Thriller              23            494       48000   
1          243.456     Drama              42            462       43200   
2         2022.400    Comedy              38            458       69400   
3          225.344     Drama              45            472       66800   
4          225.792     Drama              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [54]:
#filling na
df["Time_taken"] = df.Time_taken.fillna(np.mean(df.Time_taken))

In [55]:
# creating dummy variables
df = pd.get_dummies(df, columns = ["3D_available", "Genre"], drop_first=True)

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  Time_taken           506 non-null    float64
 12  Twitter_hastags      506 non-null    float64
 13  Avg_age_actors       506 non-null    int64  
 14  Num_multiplex        506 non-null    int64  
 15  Collection           506 non-null    int

In [59]:
#X-y split
X = df.loc[:, df.columns != "Start_Tech_Oscar"]
y = df["Start_Tech_Oscar"]

In [61]:
#train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)b

In [62]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(404, 20) (102, 20) (404,) (102,)


In [64]:
#standardization
sc = StandardScaler().fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [65]:
X_train_std

array([[-0.37257438, -0.70492455,  0.42487874, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39709866, -0.04487755,  1.24185891, ..., -0.66547513,
        -0.48525664, -0.75225758],
       [-0.402693  , -0.88675963,  1.11148974, ...,  1.50268577,
        -0.48525664, -0.75225758],
       ...,
       [-0.39805586, -0.15941933,  0.0772276 , ..., -0.66547513,
        -0.48525664, -0.75225758],
       [-0.38842357, -0.60326872,  0.93766417, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39951258, -1.01275558,  0.3988049 , ..., -0.66547513,
        -0.48525664,  1.3293319 ]])

In [73]:
X_test_std

array([[-0.40835869, -1.12872913,  0.83336883, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [ 0.71925111,  0.9988844 , -0.65283979, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40257488,  0.39610829,  0.05115377, ...,  1.50268577,
        -0.48525664, -0.75225758],
       ...,
       [-0.3982601 , -0.85812418,  0.89420778, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39934279, -0.07637654,  0.58132175, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40088071, -0.36702631,  0.31189212, ..., -0.66547513,
        -0.48525664, -0.75225758]])

### Training the model with SVM classifier

In [67]:
from sklearn.svm import SVC

In [78]:
svm = SVC(kernel = "linear", C = 0.01)
svm.fit(X_train_std, y_train)

SVC(C=0.01, kernel='linear')

In [79]:
y_pred = svm.predict(X_test_std)
y_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0], dtype=int64)

In [81]:
#model performance
#for classification we use accuracy and confusion_matrix to evaluate
from sklearn.metrics import accuracy_score, confusion_matrix

In [82]:
accuracy_score(y_test, y_pred)

0.6274509803921569

In [83]:
confusion_matrix(y_test, y_pred)
#REMEMBER
#[true positives, false positives]
#[false negatives, true negatives]

array([[11, 33],
       [ 5, 53]], dtype=int64)

In [84]:
svm.n_support_ #get the number of support vectors

array([186, 189])

## Hyperparameter tuning

In [85]:
from sklearn.model_selection import GridSearchCV

In [86]:
params = {"C": (0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50, 100, 500, 1000)}
params

{'C': (0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50, 100, 500, 1000)}

In [89]:
svm = SVC(kernel = "linear") #create object classifier

In [90]:
#(estimator, cv = cross validations, verbose = 1 the number of messages while trainig)
svm_grid = GridSearchCV(svm, params, n_jobs = -1, cv = 10, verbose = 1, scoring = "accuracy")

In [91]:
svm_grid.fit(X_train_std, y_train)

Fitting 10 folds for each of 13 candidates, totalling 130 fits


GridSearchCV(cv=10, estimator=SVC(kernel='linear'), n_jobs=-1,
             param_grid={'C': (0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50,
                               100, 500, 1000)},
             scoring='accuracy', verbose=1)

In [92]:
svm_grid.best_params_

{'C': 0.1}

In [94]:
linear_svm = svm_grid.best_estimator_ #to fit the model with optimized parameter, you have to create a new object with best_estimator_ attribute of grid search
type(linear_svm)

sklearn.svm._classes.SVC

In [95]:
y_pred = linear_svm.predict(X_test_std)
y_pred

array([1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0], dtype=int64)

In [96]:
accuracy_score(y_test, y_pred) #because sample size is small, grid search does not much make sense and it will not be much sensitive to other results, this is why we do not get much improvement

0.5980392156862745

## Polynomial Kernel

In [97]:
svm_poly = SVC(kernel = "poly", degree = 2, C = 0.1) #for polynomial you have to specify the degree power which will determine the hyperplane flexibility
svm_poly.fit(X_train_std, y_train)

SVC(C=0.1, degree=2, kernel='poly')

In [98]:
y_pred = svm_poly.predict(X_test_std)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [99]:
accuracy_score(y_test, y_pred)

0.5588235294117647

In [100]:
confusion_matrix(y_test, y_pred)

array([[ 0, 44],
       [ 1, 57]], dtype=int64)

In [101]:
svm_poly.n_support_

array([185, 194])

## Radial Kernel

In [103]:
svm_rad = SVC(kernel = "rbf", gamma = 0.5, C = 10) #rbf is radial kernel, gamma is the hyperparameter for radial that controls the kernel size, C the cost applied to cost function of vectors

In [105]:
svm_rad.fit(X_train_std, y_train)

SVC(C=10, gamma=0.5)

In [107]:
y_pred = svm_rad.predict(X_test_std)
y_pred

array([1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0], dtype=int64)

In [108]:
accuracy_score(y_test, y_pred)

0.6176470588235294

In [109]:
confusion_matrix(y_test, y_pred)

array([[16, 28],
       [11, 47]], dtype=int64)

In [110]:
svm_rad.n_support_

array([186, 218])

## Grid search for radial kernel

In [112]:
params = {"C": (0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50),
         "gamma": (0.001, 0.01, 0.1, 0.5, 1)}
params

{'C': (0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50),
 'gamma': (0.001, 0.01, 0.1, 0.5, 1)}

In [113]:
svm_rad = SVC(kernel = "rbf") #assign object classifier

In [114]:
grid_search = GridSearchCV(svm_rad, params, n_jobs = -1, verbose = 1, scoring = "accuracy")

In [116]:
grid_search.fit(X_train_std, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits


GridSearchCV(estimator=SVC(), n_jobs=-1,
             param_grid={'C': (0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50),
                         'gamma': (0.001, 0.01, 0.1, 0.5, 1)},
             scoring='accuracy', verbose=1)

In [117]:
grid_search.best_params_

{'C': 5, 'gamma': 0.01}

In [118]:
svm_rad_opt = grid_search.best_estimator_ #creat an object classifier with the model with optimized parameters

In [120]:
y_pred = svm_rad_opt.predict(X_test_std)
y_pred

array([1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0], dtype=int64)

In [121]:
accuracy_score(y_test, y_pred)

0.6078431372549019