In [ ]:
#run code fromp revious lecture
%run "Lecture_14 (Implementing Logistic Regression).ipynb"

In [4]:
X_train.head()

price  resid_area  air_qual  room_num   age  teachers  poor_prop  \
220   26.7       36.20     0.507     6.951  88.5      22.6       9.71   
71    21.7       40.81     0.413     5.961  17.5      20.8       9.88   
240   27.0       34.93     0.428     6.897  54.3      23.4      11.38   
6     22.9       37.87     0.524     6.012  66.6      24.8      12.43   
417   10.4       48.10     0.679     5.304  89.1      19.8      26.64   

     n_hos_beds  n_hot_rooms  rainfall     parks  avg_dist  airport_YES  \
220       8.734      11.2136        23  0.053540    2.8600            0   
71       10.034      13.1736        46  0.039985    5.2875            0   
240      10.240      11.2160        24  0.038641    6.3350            1   
6         6.958      12.1832        41  0.052170    5.5600            1   
417       8.608      15.0832        60  0.058835    1.6500            1   

     waterbody_Lake  waterbody_Lake and River  waterbody_River  
220               0                         0                1  
71                0                         1                0  
240               0                         0                0  
6                 0                         0                1  
417               0                         1                0

In [6]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(X_train) #object classifier
X_train_scaled = scaler.transform(X_train) #scale the train dataset

In [8]:
X_train_scaled #the scaled data is transformed from a dataframe to an array of arrays

array([[ 0.44572353, -0.70492455, -0.42487874, ..., -0.48525664,
        -0.40529635,  1.3293319 ],
       [-0.09643431, -0.04487755, -1.24185891, ..., -0.48525664,
         2.4673304 , -0.75225758],
       [ 0.478253  , -0.88675963, -1.11148974, ..., -0.48525664,
        -0.40529635, -0.75225758],
       ...,
       [-0.36751323, -0.15941933, -0.0772276 , ..., -0.48525664,
         2.4673304 , -0.75225758],
       [-0.64943531, -0.60326872, -0.93766417, ..., -0.48525664,
        -0.40529635,  1.3293319 ],
       [ 0.05536988, -1.01275558, -0.3988049 , ..., -0.48525664,
        -0.40529635,  1.3293319 ]])

In [11]:
scaler = preprocessing.StandardScaler().fit(X_test)
X_test_scaled = scaler.transform(X_test) #scale the test dataset

In [12]:
#import knn function from sklearn
from sklearn.neighbors import KNeighborsClassifier
knn_1 = KNeighborsClassifier(n_neighbors = 1) #you specify the hyperparameters when assigning the object class
knn_1.fit(X_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=1)

In [13]:
#compute confusion matrix
confusion_matrix(y_test, knn_1.predict(X_test_scaled))

#remember:
#[true positives, false positives]
#[false negatives, true negatives]

array([[30, 28],
       [19, 25]], dtype=int64)

In [15]:
#calculate accuracy score (remember that it is calculated as the true predicted values / total number of obs.)
accuracy_score(y_test, knn_1.predict(X_test_scaled))

0.5392156862745098

In [17]:
# change the hyperparameter k 
knn_3 = KNeighborsClassifier(n_neighbors = 3)
knn_3.fit(X_train_scaled, y_train)
accuracy_score(y_test, knn_1.predict(X_test_scaled))

0.5392156862745098

### Run KNN for a given range of K-values to find the optimal

In [18]:
#import GridSearchCV to run given model with a grid of parameters
from sklearn.model_selection import GridSearchCV

In [28]:
params = {"n_neighbors": np.arange(1, 11, dtype = int)} #the grid search cv will require an array of param in form of dictionary
params

{'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])}

In [31]:
grid_search_cv = GridSearchCV(KNeighborsClassifier(), params) #(estimator, param_grid)
grid_search_cv

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])})

In [32]:
grid_search_cv.fit(X_train_scaled, y_train) #now fit the model with the grid search

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])})

In [35]:
pd.DataFrame(grid_search_cv.cv_results_)

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.001197      0.000747         0.004587        0.001017   
1       0.001196      0.000399         0.007387        0.005519   
2       0.000603      0.000492         0.003303        0.001867   
3       0.000000      0.000000         0.000000        0.000000   
4       0.000000      0.000000         0.006248        0.007652   
5       0.000000      0.000000         0.003125        0.006250   
6       0.000000      0.000000         0.003124        0.006249   
7       0.000000      0.000000         0.003124        0.006248   
8       0.000000      0.000000         0.006248        0.007652   
9       0.000000      0.000000         0.006249        0.007653   

  param_n_neighbors               params  split0_test_score  \
0                 1   {'n_neighbors': 1}           0.518519   
1                 2   {'n_neighbors': 2}           0.555556   
2                 3   {'n_neighbors': 3}           0.530864   
3                 4   {'n_neighbors': 4}           0.506173   
4                 5   {'n_neighbors': 5}           0.567901   
5                 6   {'n_neighbors': 6}           0.530864   
6                 7   {'n_neighbors': 7}           0.518519   
7                 8   {'n_neighbors': 8}           0.506173   
8                 9   {'n_neighbors': 9}           0.530864   
9                10  {'n_neighbors': 10}           0.555556   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.567901           0.518519           0.530864             0.5250   
1           0.580247           0.592593           0.592593             0.5500   
2           0.592593           0.617284           0.617284             0.6125   
3           0.580247           0.592593           0.641975             0.6250   
4           0.506173           0.592593           0.666667             0.6375   
5           0.555556           0.580247           0.666667             0.6500   
6           0.506173           0.604938           0.629630             0.6375   
7           0.567901           0.604938           0.604938             0.6750   
8           0.530864           0.555556           0.641975             0.7250   
9           0.518519           0.543210           0.617284             0.6875   

   mean_test_score  std_test_score  rank_test_score  
0         0.532160        0.018453               10  
1         0.574198        0.018146                9  
2         0.594105        0.032908                4  
3         0.589198        0.047015                6  
4         0.594167        0.055802                3  
5         0.596667        0.052980                2  
6         0.579352        0.055892                8  
7         0.591790        0.055083                5  
8         0.596852        0.075990                1  
9         0.584414        0.060959                7

In [36]:
grid_search_cv.best_params_ #get the best parameter withe the best_params_ attribute

{'n_neighbors': 9}

In [39]:
optimized_knn = grid_search_cv.best_estimator_ #assign to an object the grid search best estimator
optimized_knn

KNeighborsClassifier(n_neighbors=9)

In [42]:
type(optimized_knn)

sklearn.neighbors._classification.KNeighborsClassifier

In [41]:
y_test_pred = optimized_knn.predict(X_test_scaled) #note that you can use the optimized_knn object to predict because the object will retain its model class, but now with optimized/tuned to the best parameter
y_test_pred

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1], dtype=int64)

In [43]:
confusion_matrix(y_test, y_test_pred)
#Remember:
#[true positives, false positives]
#[false negatives, true negatives]

array([[36, 22],
       [18, 26]], dtype=int64)

In [44]:
accuracy_score(y_test, y_test_pred) #note that the accuracy improved with optimzed k

0.6078431372549019

### You can specify a wider range of K parameters to test for the best optimal value