In [5]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [3]:
iris = load_iris() #load iris dataset from sklearn module

This dataset contains 3 diff types of species of irises (Setosa, Versicolor, Virginica), and four variables: Sepal Length, Sepal Width, Petal Length and Petal Width. The dataset is stored as a 150x4 np.ndarray

In [ ]:
iris #inspect the data

We will create a perceptron model with Petal Length and Petal Width as independent variables

In [9]:
X = iris.data[:, (2,3)] #get only petal length and width (2, 3) = third and fourth column; remember that indexing starts at 0!

In [ ]:
X #inspect the new data

In [8]:
iris.target #gives the categories of the dataset

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

#### Categories
* 0 setosa
* 1 versicolor
* 2 virginica

We now transform the categories into true or false based on the following conditions: if 0 (setosa), we will code as true; and if not (1 or 2 categories, versicolor and virginica respectively), we will code as false.

In [11]:
y = (iris.target == 0) #create a new variable y coding true if the irises category is 0 and false otherwise

In [12]:
y

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [13]:
y = (iris.target == 0).astype(np.int) #now we convert the trues to 0s and falses to 1s

C:\Users\davil\AppData\Local\Temp/ipykernel_6884/2023633796.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y = (iris.target == 0).astype(np.int)


In [14]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Now the X and y variables are ready, we will fit the perceptron model. We can use scikit learn to fit a single perceptron model, but to create a multi level perceptron model we have to use keras and tensorflow.

In [16]:
from sklearn.linear_model import Perceptron

In [17]:
per_clf = Perceptron(random_state = 42) #we will create a perceptron model with hyperparameter random_state as 42 (look at documentation)
#the random_state = 42 is similar to set.seed of R? If we define random_state = 42 we will always get the same result

In [18]:
per_clf.fit(X, y) #fit the perceptron model into the X and y variables

Perceptron(random_state=42)

In [19]:
y_pred = per_clf.predict(X) #predict categories based on the X independent variable
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
from sklearn.metrics import accuracy_score #import function to evaluate the model from scikit learn
accuracy_score(y, y_pred) #compute accuracy with accuracy_score(actual values, predicted values)

1.0

1.0 means 100% accuracy in classifying the species based on X independent variables

In [21]:
per_clf.coef_

array([[-1.4, -2.2]])

The perceptron model is dividing its space using a linear regression line, so we can get the coefficients of y with every variable in X. The coefficients also tell us about the impact of each variable in X in predicting y: for petal length we have a coefficient of -1.4 while for petal.width a coefficient of -2.2

In [22]:
per_clf.intercept_

array([4.])

As such, we can also get the intercept of the model